steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}"
      ]

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      [
        "run",
        "--filename=k8s",
        "--image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}",
        "--location=${_CLUSTER_LOCATION}",
        "--cluster=${_CLUSTER}"
      ]

substitutions:
  _LOCATION: us-central1
  _REPOSITORY: gke-demo-repo
  _IMAGE: demo-app
  _CLUSTER_LOCATION: us-central1
  _CLUSTER: gke-demo-cluster
options:
  logging: CLOUD_LOGGING_ONLY