steps:
  # Step 1: Build image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}",
        "."
      ]

  # Step 2: Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}"
      ]

  # Step 3: Update tfvars file in GCS bucket
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: update-tfvars
    entrypoint: bash
    args:
    - -c
    - |
      set -ex

      IMAGE_PATH="${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}"

      echo "Using image: $IMAGE_PATH"

      gsutil cp gs://${_TFVARS_BUCKET}/${_TFVARS_FILE} terraform.tfvars

      echo "Before update:"
      cat terraform.tfvars

      sed -i "s|^image *=.*|image = \"$IMAGE_PATH\"|g" terraform.tfvars

      echo "After update:"
      cat terraform.tfvars

      gsutil cp terraform.tfvars gs://${_TFVARS_BUCKET}/${_TFVARS_FILE}

  # Step 4: Invoke deploy trigger
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: invoke-deploy-trigger
    entrypoint: gcloud
    args:
      [
        "builds",
        "triggers",
        "run",
        "${_DEPLOY_TRIGGER_NAME}",
        "--region=${_LOCATION}",
        "--substitutions=_IMAGE_TAG=${SHORT_SHA}"
      ]

substitutions:
  _LOCATION: us-central1
  _REPOSITORY: gke-demo-repo
  _IMAGE: demo-app

  # Deploy trigger name
  _DEPLOY_TRIGGER_NAME: deploy-trigger

  # GCS tfvars location
  _TFVARS_BUCKET: my-tfvars-bucket
  _TFVARS_FILE: test.tfvars

options:
  logging: CLOUD_LOGGING_ONLY