apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: us-central1-docker.pkg.dev/cloud-armor-demo-491409/gke-demo-repo/demo-app:latest
          ports:
            - containerPort: 8080